### ISSUE TITLE
Youtube gdata-java-client library not working with jdk1.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gdata-java-client#206]
```
What steps will reproduce the problem?
1.Write a program to upload video in youtube(Any one of Direct upload or
browser based upload)
2.It gives compilation error in the statement in which VideoEntry object is
instanciated.
3.It works fine with jdk1.5

What is the expected output? What do you see instead?
Its working fine with jdk1.5  .   It would be better if it also works with
jdk1.4 .

What version of the product are you using? On what operating system?
I am using jdk1.4 .  Operating system : XP & Linux

Please provide any additional information below.
Our application server(WEB-SPHERE) is configured with JDK1.4 . I need a
clear idea of the api if it works with jdk1.4.

Thanks
Arnab Chakraborty.
```

Original issue reported on code.google.com by `arnab...@gmail.com` on 11 Nov 2009 at 6:44
